=== pavelkuz/BunchXml/src/main/resources/Bouquet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.com/bouquet"
           xmlns:tns="http://www.epam.com/bouquet"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
  <xs:element name="bouquet" type="tns:bouquet"/>
  <xs:complexType name="bouquet">
    <xs:sequence>
      <xs:element name="id" type="tns:UUID" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="flower" minOccurs="1" maxOccurs="unbounded">
      <xs:complexType>
        <xs:all>
          <xs:element name="id" type="tns:UUID"/>
          <xs:element name="name" type="xs:string"/>
          <xs:element name="price" type="xs:double"/>
          <xs:element name="cutDate" type="xs:date"/>
          <xs:element name="stemLength" type="xs:double"/>
          <xs:element name="color" type="xs:string"/>
        </xs:all>
      </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="UUID">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== pavelkuz/BunchXml/src/main/resources/Bouquet.xml
<?xml version="1.0" encoding="UTF-8"?>
<bouquet xmlns="http://www.epam.com/bouquet"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.epam.com/bouquet http://www.epam.com/trucks/Bouquet.xsd">
    <id>c7226349-be0a-4fcf-8142-47a489b6dbc0</id>
    <name>simple bunch</name>
    <flower>
        <id>c7226349-be0a-4fcf-8142-47a489b6dbc1</id>
        <name>rose</name>
        <price>500.75</price>
        <cutDate>2015-07-02</cutDate>
        <stemLength>75.5</stemLength>
        <color>red</color>
    </flower>
    <flower>
        <id>c7226349-be0a-4fcf-8142-47a489b6dbc2</id>
        <name>tulip</name>
        <price>150.2</price>
        <cutDate>2015-07-01</cutDate>
        <stemLength>70.3</stemLength>
        <color>yellow</color>
    </flower>
    <flower>
        <id>c7226349-be0a-4fcf-8142-47a489b6dbc3</id>
        <name>camomile</name>
        <price>50</price>
        <cutDate>2015-07-03</cutDate>
        <stemLength>72.2</stemLength>
        <color>white</color>
    </flower>
</bouquet>
